[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

fs_permissions = [{ access = "read-write", path = "./"}]

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 15000
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.20'